### ISSUE TITLE
Robomaster-Ai-challenge-2019 code problem

### ISSUE THREAD

**Issue by ghw2016z** [Robomaster-at-Berkeley/Robomaster-AI-Challenge-2019#2]
There  is  a  error  when I run  /DJI / robot_play.py.  I can  ensure my environment is right and every step is OK according to your instructions. I think maybe there is something wrong in your codes. I would appreciate it very much if you could give me a reply. Time remains less , I need the right result,  waiting online !  Thank you! 

The problem is as follows:
Traceback (most recent call last):
Traceback (most recent call last):
  File "robot_play.py", line 17, in <module>
    env.step()
  File "/home/guohaowen/.local/lib/python3.5/site-packages/gym/envs/DJI/robomaster.py", line 193, in step
    char.act()
  File "/home/guohaowen/.local/lib/python3.5/site-packages/gym/envs/DJI/Objects.py", line 424, in act
    action = strategy.decide(self)
  File "/home/guohaowen/.local/lib/python3.5/site-packages/gym/envs/DJI/strategy.py", line 106, in decide
    if keyboard.is_pressed(self.turnleft):
  File "/home/guohaowen/.local/lib/python3.5/site-packages/keyboard/__init__.py", line 415, in is_pressed
    steps = parse_hotkey(hotkey)
  File "/home/guohaowen/.local/lib/python3.5/site-packages/keyboard/__init__.py", line 342, in parse_hotkey
    scan_codes = key_to_scan_codes(hotkey)
  File "/home/guohaowen/.local/lib/python3.5/site-packages/keyboard/__init__.py", line 322, in key_to_scan_codes
    raise ValueError('Key {} is not mapped to any known key.'.format(repr(key)), e)
ValueError: ("Key 'A' is not mapped to any known key.", None)
Exception ignored in: <bound method Viewer.__del__ of <rendering.Viewer object at 0x7fdbeb423908>>
  File "/home/guohaowen/.local/lib/python3.5/site-packages/gym/envs/DJI/rendering.py", line 146, in __del__
  File "/home/guohaowen/.local/lib/python3.5/site-packages/gym/envs/DJI/rendering.py", line 62, in close
  File "/home/guohaowen/.local/lib/python3.5/site-packages/pyglet/window/xlib/__init__.py", line 474, in close
  File "/home/guohaowen/.local/lib/python3.5/site-packages/pyglet/gl/xlib.py", line 343, in destroy
  File "/home/guohaowen/.local/lib/python3.5/site-packages/pyglet/gl/base.py", line 333, in destroy
  File "/home/guohaowen/.local/lib/python3.5/site-packages/pyglet/gl/xlib.py", line 333, in detach
  File "/home/guohaowen/.local/lib/python3.5/site-packages/pyglet/gl/lib.py", line 96, in errcheck
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable

![problem](https://user-images.githubusercontent.com/47708870/54660103-ec25be80-4b0f-11e9-952d-7c9086e29773.png)

**Comment by Yibin-Li** [comment]
Sorry, this is the old version of the simulation we are using. It looks like your problem is the keyboard "A" key doesn't work. Try using arrow key?

**Comment by ghw2016z** [comment]
Thanks for your advice! I find the reason that my "keyboard" library version is new, so I replaced it with low version. Finally , it works successfully.
